### ISSUE TITLE
[Bug] `SignedMessageResponse.derivationPath` is of wrong type.

### ISSUE THREAD

**Issue by AlonzoRicardo** [fireblocks/fireblocks-sdk-js#102]
**Describe the bug**
The [SignedMessageResponse.derivationPath type](https://github.com/fireblocks/fireblocks-sdk-js/blob/4695a152543dde73eaafcb7bda146ec350669f14/src/types.ts#L371) `string` when it actually returns `number[]`.

**To Reproduce**
Fetch transaction by id and check derivation path type.

**Expected behavior**
Should be of correct type to avoid compilation errors on Typescript projects

**Version:**
 - `fireblocks-sdk` version: [e.g. 1.7.0]
 - npm version:
 - node version:

**Comment by Chengxuan** [comment]
@AlonzoRicardo @tomervil @yarinvak PR raised here: https://github.com/fireblocks/fireblocks-sdk-js/pull/108 can you take a look at it?
