### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by tahalahij** [fireblocks/fireblocks-sdk-js#103]
**Return fireblocks error message on 400 error**
I'm always frustrated when i get 400 error from fireblocks service but i have no clue what is the issue

**Describe the solution you'd like**
I have introduced a new Error called Fireblocks error and it will be returned to the caller when an error happens

**Additional context**

**Comment by yarinvak** [comment]
We added error handling section to the Readme so you can see how to retrieve the Fireblocks related data
