### ISSUE TITLE
TypeError: fireblocks.getVaultAsset is not a function

### ISSUE THREAD

**Issue by abdul-basit96** [fireblocks/fireblocks-sdk-js#11]
const vaultAsset = fireblocks.getVaultAsset(accountId, assetId);
using this function and getting error TypeError: fireblocks.getVaultAsset is not a function
while other functions are working fine

**Comment by yarinvak** [comment]
Hey there is not such operation indeed

**Comment by abdul-basit96** [comment]
But this function is mentioned in your api docs.

![Screenshot from 2020-12-07 17-12-23](https://user-images.githubusercontent.com/75294052/101349592-6af7f780-38af-11eb-9ff9-38bb0445ed44.png)

**Comment by yarinvak** [comment]
You are right it's a mistake in our documentation, the correct method to call would be `getVaultAccountAsset`

**Comment by abdul-basit96** [comment]
Thank you so much. But you have to modify your docs for the ease of developers because devlopers dont have enough time to wait for your response. Also there are few more functions which are not working but mentioned in your docs.
