### ISSUE TITLE
[Bug] Version 3.1.0 broke export/import of SDK

### ISSUE THREAD

**Issue by gregsj** [fireblocks/fireblocks-sdk-js#137]
**Describe the bug**
After the latest release I'm unable to build my application successfully and get the following error:
Error: Cannot find module '/var/app/current/node_modules/fireblocks-sdk/dist/src/fireblocks-sdk.js'. Please verify that the package.json has a valid "main" entry

**To Reproduce**
1. remove node_module
2. yarn install
3. start app

**Expected behavior**
module to be found

**Screenshots**

**Version:**
 - `fireblocks-sdk` version:  3.1.0
 - npm version: yarn ^1.22.19
 - node version: >=14.0.0

**Additional context**

**Comment by yarinvak** [comment]
Please don't use 3.1.0 in the meantime
A fix will be published soon by @YoavBZ (ver 3.1.1)

**Comment by yarinvak** [comment]
3.1.1 published with a fix @gregsj :rocket:
Thanks for reporting the issue!
