### ISSUE TITLE
[Feature Request] Fireblocks-defi-sdk support

### ISSUE THREAD

**Issue by Marxpark** [fireblocks/fireblocks-sdk-js#148]
**Is your feature request related to a problem? Please describe.**
Fireblocks-defi-sdk and the ethers bridge no longer work with latest version.

**Describe the solution you'd like**
Update the fireblocks-defi-sdk package to use the new methods.

**Additional context**
Fireblocks-defi-sdk is very convenient for ethers users, we would like to see it in use, or the ethers bridge added into this sdk.

**Comment by orenyomtov** [comment]
Hey, can you see if our newer fireblocks-web3-provider SDK meets your needs better?
https://github.com/fireblocks/fireblocks-web3-provider

And if you wish to keep using the DeFi-sdk, you can keep using ethers v5 by installing it as so:
'''
npm install ethers@5
'''

**Comment by Marxpark** [comment]
Looks very good indeed, might be even easier to use then the old bridge where we needed to implement custom populateTransaction flow for all of Fireblocks transactions. Will test it out, cheers!
