### ISSUE TITLE
Method `getMaxSpendableAmount` missing in latest 1.5.9 release

### ISSUE THREAD

**Issue by mistersimon** [fireblocks/fireblocks-sdk-js#20]
Hi Team,

The method `getMaxSpendableAmount` exists in the master branch, but it isn't there on the latest release when i pull from npm.
https://github.com/fireblocks/fireblocks-sdk-js/blob/65f09b2c15db5e8444761e804f593ee0cdf012f1/src/fireblocks-sdk.ts#L691

Any chance of updating the npm release?

Thanks,
Simon

**Comment by tomervil** [comment]
@mistersimon This issue was fixed, thanks!
