### ISSUE TITLE
wrong getSupportedAsset  return type

### ISSUE THREAD

**Issue by andpi314** [fireblocks/fireblocks-sdk-js#33]
According to the [documentation](https://docs.fireblocks.com/api/#supported-assets-object), the method [getSupportedAsset](https://github.com/fireblocks/fireblocks-sdk-js/blob/2d8de620325487a89df56dd021a719f6168fae69/src/fireblocks-sdk.ts#L66) should return a ```AssetTypeResponse```, but instead it returns a ```VaultAccountResponse```.

More detail on types:

Expected:
```ts
interface AssetTypeResponse {
    id: string
    name: string 
    type: string 
    contractAddress: string
}
```

Got: 
```ts
interface VaultAccountResponse {
    id: string;
    name: string;
    hiddenOnUI: boolean;
    assets: AssetResponse[];
    customerRefId?: string;
    autoFuel: boolean;
}
```

**Comment by tomervil** [comment]
Thanks @andpi314! Fixed in fireblocks-sdk@1.6.3
