### ISSUE TITLE
Allow asynchronous issue of jwt

### ISSUE THREAD

**Issue by Henry-bee** [fireblocks/fireblocks-sdk-js#70]
Would be great if `IAuthProvider.sigJwt` is asynchronous instead

https://github.com/fireblocks/fireblocks-sdk-js/blob/2d972cae010f2a7eabacc672b6258596417e296d/src/iauth-provider.ts#L1

**Comment by kennethtxytqw** [comment]
Engineers from [Hodlnaut](https://www.hodlnaut.com/) will be happy to have this too!

**Comment by yarinvak** [comment]
can you please elaborate with your use case?

**Comment by yarinvak** [comment]
Closing it for now due to lack of response, please reopen when you can elaborate on the use case

**Comment by Henry-bee** [comment]
Sorry for the late response.

I believe some users would like to inject their own Token provider and in some instance, signing jwt is an asynchronous process. For instance, signing jwt via a cloud provider
