### ISSUE TITLE
[Feature Request] Allow the txId parameter to be either a transaction hash or a fireblocks id in POST /v1/webhooks/resend/{txId} 

### ISSUE THREAD

**Issue by dimastelian** [fireblocks/fireblocks-sdk-js#84]
The documentation for POST /v1/webhooks/resend/{txId} is vague:
https://docs.fireblocks.com/api/#resend-missed-webhooks-per-transaction

One would expect that txId is actually a blockchain transaction hash, not a fireblocks id, but sending a tx hash returns a 404 error.

It would be useful if we could actually send tx hash for the case when a customer reports their tx hash transaction didn't get processed on our backend, and we don't actually know the fireblocks Id for that transaction.

**Comment by yarinvak** [comment]
`txId` across our documentation and system represents a Fireblocks ID, and not `txHash`, which would be mentioned explicitly as `txHash`
