### ISSUE TITLE
[Bug] Missing sourceAddress in TransactionResponse

### ISSUE THREAD

**Issue by prevostc** [fireblocks/fireblocks-sdk-js#85]
**Describe the bug**
Typescript type doesn't match the returned value.
- https://docs.fireblocks.com/api/#list-transactions have sourceAddress
- Typescript type doesn't have this field

**To Reproduce**
Do this
```
const transactions = await fireblocks.getTransactions({
        status: args.status,
        after: from
});
```
Compare the return value with the TransactionResponse type. They don't match.

**Expected behavior**
Ts type should match the API response more closely and provide similar data structures.

**Version:**
 - `fireblocks-sdk` version: 2.0.0
 - Now using node v16.14.0 (npm v8.3.1)

**Comment by yarinvak** [comment]
A fix is released in v2.3.1
