### ISSUE TITLE
Wrong response type to `getExchangeAsset` SDK function

### ISSUE THREAD

**Issue by elhayra** [fireblocks/fireblocks-sdk-js#90]
The response type of `getExchangeAsset()` should probably be `AssetResponse` and not `ExchangeResponse`. The actual server response structure is correct, only the type is wrong. See reference below.

https://github.com/fireblocks/fireblocks-sdk-js/blob/29964a8c6890d0ece18f713c5536d0c968476b77/src/fireblocks-sdk.ts#L231

**Comment by yarinvak** [comment]
This was fixed in v3.0
